Remove erroring out when checks on errors exists
rancher/server-chart pull request #46
Opened 2018-11-07 19:52 UTC by superseb

Error codes are checked in the script but script fails because of error before error condition can be checked

2018-11-08 04:42 UTC, deniseschannon commented
@superseb can you make a rancher issue for what this is fixing?

2018-12-03 21:45 UTC, jgreat requested changes
I'm confused.  This has to error out or the checks won't work. They should stop the build process if they fail.

2018-12-03 21:58 UTC, superseb commented
You check for return codes after the commands and explain what's wrong, but it never ends up there if you exit on error because it exists before you check the return code.

2018-12-03 22:26 UTC, jgreat commented
OK I think I see where you are going with this. The checks for helm functionality are not really working as intended because of the set -e.

2018-12-03 22:26 UTC, jgreat approved these changes

2018-12-19 18:20 UTC, merged